### ISSUE TITLE
Not working on Ubuntu 16.04 - 18.04

### ISSUE THREAD

**Issue by harrydrippin** [choms46/faceMoji#1]
Thank you for the nice app!

Your web application is not working on Chrome, Ubuntu above 16.04.
Your FaceMoji keeps breaking above UI.

Please fix this! :)

**Comment by jaycho46** [comment]
Thank you for your attention.

This repository is deprecated. 
You can still using this application on latest version of iOS or macOS. 

Pull requests are always welcome!
